spring:
  profiles: qa

name: raju  name from qa profiles and application.yml

---
spring:
  profiles: dev

name: raju  name from dev profiles and application.yml

---
spring:
  profile: prod

name: kaju from prod

