spring:
  profiles: qa-hen

name: raju  name from qa profiles and application.yml
msg: prod msg global from qa-hen

---
spring:
  profiles: dev

name: raju  name from dev profiles changed and application.yml

---
spring:
  profile: prod

name: kaju from prod global  sdsd
msg: prod msg global
email: raju@gmaieel.com from global  dev profile

