spring:
  profiles: qa-hen

name: raju  name from qa profiles and rtrtrapplication.yml
msg: prod msg global from qa-hen

---
spring:
  profiles: dev

name: raju  name from dev profiles changed and rtrtrapplication.yml

---
spring:
  profile: prod

name: kaju from prod global
msg: prod msg global

